### ISSUE TITLE
Wire up circle-ci for linting and tests on each PR?

### ISSUE THREAD

**Issue by pdehaan** [motin/esper-pioneer-shield-study#19]
Looks like the stubs are there, but not sure if it's worth enabling to make sure any future PRs don't break linting or web-ext or tests...

But since it's a short lived Pioneer experiment, it may not be worth it. 🤷‍♀️

**Comment by motin** [comment]
For the current launch if the ESPER experiment, it seems a bit overkill since the code has already passed QA previously. Will close this issue for the time being, but re-open it when/if future iterations of the ESPER experiment become relevant. (Most likely after the new template and move to web extensions is done)
